name: Elixir CI

on:
  push:
    branches: ["main"] # adapt branch for project
  pull_request:
    branches: ["main"] # adapt branch for project

env:
  MIX_ENV: test

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        otp: ["27.3.4"]
        elixir: ["1.18.4"]

    name: Test on OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}} (${{matrix.os}})
    runs-on: ${{matrix.os}}
    steps:
      - name: ☁️ Checkout repository
        uses: actions/checkout@v4

      - name: 💧 Setup Elixir
        uses: marmelasoft/elixir-setup@main
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
          cache-plts: true

      - name: 🔬 Run unit tests
        run: mix test --exclude e2e --all-warnings --warnings-as-errors

      - name: 🌐 Run e2e tests
        run: mix test --only e2e --all-warnings --warnings-as-errors

      - name: 💡 Lint the code
        run: mix credo --strict --all

      - name: 🔍 Analyze code
        run: mix dialyzer --format github

      - name: 🛡️ Search vulnerabilities
        run: |
          mix hex.audit
          mix deps.audit
          mix sobelow --skip --exit --threshold high

      - name: ♻️ Check unused dependencies
        run: mix deps.unlock --check-unused
